name: ci-javascript-workflow

on:
  pull_request:
    branches:
      - develop

jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21

      - run: node --test **/*.spec.mjs
      - run: node math.mjs

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          
          push: false
          tags: yuridefranca/ci-javascript:latest
